import { createClient } from "@supabase/supabase-js";

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const configured = supabaseUrl?.startsWith("https://") && supabaseKey?.startsWith("sb_publishable_");
const supabase = configured ? createClient(supabaseUrl, supabaseKey) : null;

const rarities=[
  {id:'common',name:'Comum',color:'#9aa0b6',count:45,packChance:65,size:'1–2',guarantee:'1 comum ou melhor'},
  {id:'uncommon',name:'Incomum',color:'#5fe0a1',count:24,packChance:20,size:'3',guarantee:'1 incomum ou melhor'},
  {id:'rare',name:'Rara',color:'#53b8ff',count:14,packChance:8,size:'4–5',guarantee:'1 rara ou melhor'},
  {id:'epic',name:'Épica',color:'#b277ff',count:8,packChance:4,size:'6',guarantee:'1 épica ou melhor'},
  {id:'mythic',name:'Mítica',color:'#ff6eb5',count:4,packChance:2,size:'7',guarantee:'1 mítica ou melhor'},
  {id:'legendary',name:'Lendária',color:'#ffd75f',count:2,packChance:.8,size:'10',guarantee:'1 lendária exclusiva'},
  {id:'secret',name:'Secreta',color:'#ff775f',count:3,packChance:.2,size:'10',guarantee:'1 lendária + 1 secreta'}
];
const juiceRewards={common:2,uncommon:4,rare:7,epic:12,mythic:20,legendary:35,secret:60};
const icons=['🌙','🪐','☄️','🛸','👾','🔭','🌌','🌞','🌎','🛰️','👽','🚀','⭐','🌠','🌑','🌈','🔥','💫','🦄','🐉','🦊','🐋','🦋','🐙','🦖','🦁','🐺','🐝','🦉','🐢','🍄','🌵','🌻','🌊','❄️','⚡','💎','🔮','🗿','🏰','🎭','🎪','🎸','🧭','⏳','🧿','👑','🗝️','⚔️','🛡️'];
const adjectives=['Lunar','Estelar','Nebuloso','Solar','Galáctico','Cósmico','Astral','Radiante','Abissal','Celeste'];
const subjects=['Viajante','Guardião','Oráculo','Cometa','Dragão','Raposa','Titã','Farol','Nave','Relíquia'];
const descriptions=['Diz-se que aparece quando uma nova estrela nasce.','Cruza galáxias guardando histórias esquecidas.','Sua luz muda de cor a cada órbita completa.','Um achado raro vindo dos limites do universo.','Carrega no brilho a memória de mundos distantes.'];
const cards=[];let seq=0;
rarities.forEach((r,ri)=>{for(let j=0;j<r.count;j++){cards.push({id:++seq,rarity:r.id,name:`${subjects[(j*3+ri)%subjects.length]} ${adjectives[(j+ri*2)%adjectives.length]}`,icon:icons[(seq*7+ri*3)%icons.length],description:descriptions[(j+ri)%descriptions.length]})}});
const state={owned:{},juice:0,lastOpened:null,packs:0};
let currentFilter='all',currentRarity='all',currentUser=null,registerMode=false,dailyAvailable=false;
const byId=id=>document.getElementById(id);const rarity=id=>rarities.find(r=>r.id===id);

function stats(){const unique=Object.keys(state.owned).filter(k=>state.owned[k]>0).length,total=Object.values(state.owned).reduce((a,b)=>a+b,0);return{unique,total,dupes:Math.max(0,total-unique)}}
function renderStats(){const s=stats();byId('ownedCount').textContent=s.unique;byId('percentStat').textContent=s.unique+'%';byId('dupeStat').textContent=s.dupes;byId('juiceBalance').textContent=state.juice;byId('buyMystery').disabled=state.juice<30;document.querySelector('.progress-fill').style.width=s.unique+'%';document.querySelector('.progress-track').setAttribute('aria-valuenow',s.unique);byId('collectionCopy').textContent=s.unique===100?'Coleção completa. Você conquistou o cosmos!':`${100-s.unique} descobertas faltam — as secretas só aparecem depois de encontradas.`}
function renderAlbum(){const grid=byId('albumGrid');const filtered=cards.filter(c=>{const owned=!!state.owned[c.id];if(c.rarity==='secret'&&!owned)return false;return(currentFilter==='all'||(currentFilter==='owned'&&owned)||(currentFilter==='missing'&&!owned))&&(currentRarity==='all'||c.rarity===currentRarity)});grid.innerHTML=filtered.length?'':'<div class="empty">Nenhuma figurinha combina com este filtro. As secretas só surgem quando descobertas.</div>';filtered.forEach(c=>{const r=rarity(c.rarity),owned=!!state.owned[c.id],b=document.createElement('button');b.className='sticker '+(owned?'':'locked');b.style.setProperty('--rarity',r.color);b.innerHTML=`<span class="sticker-number">#${String(c.id).padStart(3,'0')}</span><span class="sticker-badge">${r.name}</span>${state.owned[c.id]>1?`<span class="dupe">+${state.owned[c.id]-1}</span>`:''}<span class="sticker-visual">${owned?c.icon:'✦'}</span><span class="sticker-info"><span class="sticker-name">${owned?c.name:'Figurinha oculta'}</span><span class="sticker-rarity">${r.name}</span></span>`;b.disabled=!owned;b.setAttribute('aria-label',owned?`${c.name}, ${r.name}`:`Figurinha ${c.id} ainda não encontrada`);if(owned)b.onclick=()=>showDetail(c);grid.appendChild(b)})}
function renderOdds(){const rows=(metric,max,formatter)=>rarities.map(r=>`<div class="prob-row"><span class="rarity-key"><i class="dot" style="--c:${r.color}"></i>${r.name}</span><span class="bar"><i style="--c:${r.color};--w:${(r[metric]/max)*100}%"></i></span><b>${formatter(r[metric])}</b></div>`).join('');byId('packOdds').innerHTML=rows('packChance',65,n=>n+'%');byId('stickerOdds').innerHTML=rows('count',45,n=>n+'%');byId('packRules').innerHTML=rarities.map(r=>`<tr><td><span class="rarity-key"><i class="dot" style="--c:${r.color}"></i>${r.name}</span></td><td>${r.size} figurinhas</td><td>${r.guarantee}</td><td><strong>+${juiceRewards[r.id]} 🧃</strong></td></tr>`).join('');byId('rarityFilter').innerHTML='<option value="all">Toda raridade</option>'+rarities.filter(r=>r.id!=='secret'||cards.some(c=>c.rarity==='secret'&&state.owned[c.id])).map(r=>`<option value="${r.id}">${r.name}</option>`).join('')}
function updateDaily(){const btn=byId('openPack');btn.disabled=!dailyAvailable;btn.textContent=dailyAvailable?'Abrir pacote grátis':'Pacote de hoje aberto';byId('packMessage').textContent=dailyAvailable?'Um pacote está esperando por você.':'Volte amanhã para uma nova surpresa.';byId('countdown').textContent=dailyAvailable?'Disponível agora':'Novo pacote à meia-noite'}
function renderAll(){renderStats();renderAlbum();updateDaily()}
function openModal(id){byId(id).classList.add('open');byId(id).querySelector('.close').focus();document.body.style.overflow='hidden'}
function closeModal(id){byId(id).classList.remove('open');document.body.style.overflow=''}
function showDetail(c){const r=rarity(c.rarity);byId('detailIcon').textContent=c.icon;byId('detailRarity').textContent=`#${String(c.id).padStart(3,'0')} · ${r.name}`;byId('detailRarity').style.color=r.color;byId('detailTitle').textContent=c.name;byId('detailText').textContent=c.description+(state.owned[c.id]>1?` Você possui ${state.owned[c.id]} cópias.`:'');openModal('detailModal')}
function burst(){const box=byId('confetti'),colors=rarities.map(r=>r.color);box.innerHTML='';for(let i=0;i<42;i++){const p=document.createElement('i');p.style.cssText=`left:${Math.random()*100}%;--x:${(Math.random()-.5)*300}px;--c:${colors[i%colors.length]};animation-delay:${Math.random()*.4}s`;box.appendChild(p)}setTimeout(()=>box.innerHTML='',2500)}
function showPack(data,source){const payload=typeof data==='string'?JSON.parse(data):data;Object.assign(state,payload.state);dailyAvailable=payload.daily_available;const tier=rarities.findIndex(r=>r.id===payload.pack_tier),entries=payload.entries.map(e=>({card:cards.find(c=>c.id===e.id),isNew:e.is_new})),newCount=entries.filter(e=>e.isNew).length;byId('revealTier').textContent=`${source==='mystery'?'Pacote misterioso revelou: ':''}Pacote ${payload.pack_rarity}`;byId('revealTier').style.color=rarities[tier].color;byId('revealSummary').textContent=`${newCount?`${newCount} ${newCount===1?'nova figurinha':'novas figurinhas'}`:'Somente repetidas'}${payload.reward?` · +${payload.reward} 🧃`:' '}`;byId('revealGrid').innerHTML='';entries.forEach(({card:c,isNew},i)=>{const r=rarity(c.rarity),el=document.createElement('div');el.className='reveal-card';el.style.cssText=`--rarity:${r.color};animation-delay:${i*.08}s`;el.innerHTML=`<div><div class="icon">${c.icon}</div><b>${c.name}</b><small>${r.name}</small>${isNew?'<div class="new-tag">NOVA</div>':''}</div>`;byId('revealGrid').appendChild(el)});openModal('revealModal');if(tier>=4||newCount>=3)burst();renderOdds();renderAll();return payload}
async function openPack(source){const {data,error}=await supabase.rpc('open_album_pack',{p_source:source});if(error)throw error;return showPack(data,source)}
async function openDaily(){if(!dailyAvailable)return;byId('openPack').disabled=true;try{return await openPack('daily')}catch(error){alert(error.message);updateDaily()}}
async function buyMystery(){if(state.juice<30)return;byId('buyMystery').disabled=true;try{return await openPack('mystery')}catch(error){alert(error.message);renderStats()}}
async function loadProfile(user){const [{data:profile,error:pError},{data:progress,error:gError}]=await Promise.all([supabase.from('profiles').select('name,email').eq('id',user.id).single(),supabase.from('album_progress').select('owned,coins,last_daily_pack,packs_opened').eq('user_id',user.id).single()]);if(pError)throw pError;if(gError)throw gError;currentUser=user;state.owned=progress.owned||{};state.juice=progress.coins||0;state.lastOpened=progress.last_daily_pack;state.packs=progress.packs_opened||0;dailyAvailable=progress.last_daily_pack!==new Intl.DateTimeFormat('en-CA',{timeZone:'America/Fortaleza'}).format(new Date());byId('accountEmail').textContent=profile.name||profile.email;byId('authGate').classList.add('ready');renderOdds();renderAll()}
async function handleAuth(event){event.preventDefault();const email=byId('authEmail').value.trim(),password=byId('authPassword').value,name=byId('authName').value.trim(),button=byId('authSubmit');byId('authError').textContent='';button.disabled=true;button.textContent=registerMode?'Criando conta…':'Entrando…';try{if(registerMode){const {data,error}=await supabase.auth.signUp({email,password,options:{data:{name}}});if(error)throw error;if(!data.session){byId('authError').style.color='#5fe0a1';byId('authError').textContent='Conta criada! Confirme o e-mail para entrar.';return}}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error}}catch(error){byId('authError').style.color='#ff9a8b';byId('authError').textContent=error.message}finally{button.disabled=false;button.textContent=registerMode?'Criar conta':'Entrar'}}
function toggleAuth(){registerMode=!registerMode;byId('authTitle').textContent=registerMode?'Criar sua conta':'Entrar no álbum';byId('nameField').style.display=registerMode?'block':'none';byId('authName').required=registerMode;byId('authPassword').autocomplete=registerMode?'new-password':'current-password';byId('authSubmit').textContent=registerMode?'Criar conta':'Entrar';byId('authToggle').textContent=registerMode?'Já tenho uma conta':'Ainda não tenho conta';byId('authError').textContent=''}
async function initialize(){if(!configured){byId('authMessage').textContent='Conecte as variáveis do Supabase para iniciar.';byId('authError').textContent='VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY não configuradas.';byId('authSubmit').disabled=true;return}const {data:{session}}=await supabase.auth.getSession();if(session)await loadProfile(session.user);supabase.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_IN'&&session)setTimeout(()=>loadProfile(session.user),0);if(event==='SIGNED_OUT')location.reload()})}

document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-jump]').forEach(x=>x.classList.toggle('active',x===b));byId(b.dataset.jump).scrollIntoView({behavior:'smooth'})});
document.querySelectorAll('.filter[data-filter]').forEach(b=>b.onclick=()=>{currentFilter=b.dataset.filter;document.querySelectorAll('.filter[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderAlbum()});
byId('rarityFilter').onchange=e=>{currentRarity=e.target.value;renderAlbum()};byId('openPack').onclick=openDaily;byId('buyMystery').onclick=buyMystery;byId('showRules').onclick=()=>openModal('rulesModal');
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModal(m.id)});document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal.open').forEach(m=>closeModal(m.id))});
byId('authForm').addEventListener('submit',handleAuth);byId('authToggle').onclick=toggleAuth;byId('logoutButton').onclick=async e=>{e.preventDefault();await supabase?.auth.signOut()};
renderOdds();renderAll();initialize();
