create table if not exists public.social_profiles (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  handle text not null unique check (handle ~ '^[a-z0-9_]{3,24}$'),
  display_name text not null check (char_length(display_name) between 1 and 80),
  featured_card integer check (featured_card between 1 and 110),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.social_profiles(user_id) on delete cascade,
  addressee_id uuid not null references public.social_profiles(user_id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (requester_id <> addressee_id),
  unique (requester_id, addressee_id)
);

create table if not exists public.feed_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.social_profiles(user_id) on delete cascade,
  card_id integer not null check (card_id between 1 and 110),
  caption text not null default '' check (char_length(caption) <= 180),
  created_at timestamptz not null default now()
);

create table if not exists public.sticker_trades (
  id bigint generated by default as identity primary key,
  proposer_id uuid not null references public.social_profiles(user_id) on delete cascade,
  recipient_id uuid not null references public.social_profiles(user_id) on delete cascade,
  offered_card_id integer not null check (offered_card_id between 1 and 110),
  requested_card_id integer not null check (requested_card_id between 1 and 110),
  status text not null default 'pending' check (status in ('pending','accepted','rejected','cancelled')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  check (proposer_id <> recipient_id)
);

alter table public.social_profiles enable row level security;
alter table public.friendships enable row level security;
alter table public.feed_posts enable row level security;
alter table public.sticker_trades enable row level security;

create policy "Authenticated users read social profiles" on public.social_profiles
for select to authenticated using (true);
create policy "Users update own social profile" on public.social_profiles
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users read own friendships" on public.friendships
for select to authenticated using (auth.uid() in (requester_id, addressee_id));

create policy "Friends read feed posts" on public.feed_posts
for select to authenticated using (
  user_id = auth.uid() or exists (
    select 1 from public.friendships f
    where f.status = 'accepted'
      and ((f.requester_id = auth.uid() and f.addressee_id = feed_posts.user_id)
        or (f.addressee_id = auth.uid() and f.requester_id = feed_posts.user_id))
  )
);
create policy "Users delete own feed posts" on public.feed_posts
for delete to authenticated using (auth.uid() = user_id);

create policy "Users read own trades" on public.sticker_trades
for select to authenticated using (auth.uid() in (proposer_id, recipient_id));

create policy "Users read friend albums" on public.album_progress
for select to authenticated using (
  auth.uid() = user_id or exists (
    select 1 from public.friendships f
    where f.status = 'accepted'
      and ((f.requester_id = auth.uid() and f.addressee_id = album_progress.user_id)
        or (f.addressee_id = auth.uid() and f.requester_id = album_progress.user_id))
  )
);

create or replace function public.safe_social_handle(p_name text, p_id uuid)
returns text language sql immutable as $$
  select left(regexp_replace(lower(coalesce(nullif(trim(p_name),''),'colecionador')), '[^a-z0-9]+', '_', 'g'), 17)
    || '_' || left(replace(p_id::text,'-',''), 6)
$$;

insert into public.social_profiles (user_id, handle, display_name)
select p.id, public.safe_social_handle(p.name, p.id), p.name
from public.profiles p
on conflict (user_id) do nothing;

create or replace function public.create_social_profile_for_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.social_profiles (user_id, handle, display_name)
  values (new.id, public.safe_social_handle(new.name, new.id), new.name)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_profile_created_social on public.profiles;
create trigger on_profile_created_social after insert on public.profiles
for each row execute procedure public.create_social_profile_for_user();

create or replace function public.set_featured_sticker(p_card_id integer)
returns void language plpgsql security definer set search_path = public as $$
declare owned_count integer;
begin
  if auth.uid() is null then raise exception 'Faça login para continuar'; end if;
  select coalesce((owned ->> p_card_id::text)::integer,0) into owned_count
  from public.album_progress where user_id = auth.uid();
  if owned_count < 1 then raise exception 'Você ainda não possui esta figurinha'; end if;
  update public.social_profiles set featured_card = p_card_id, updated_at = now() where user_id = auth.uid();
end;
$$;

create or replace function public.publish_sticker(p_card_id integer, p_caption text default '')
returns bigint language plpgsql security definer set search_path = public as $$
declare owned_count integer; new_id bigint;
begin
  if auth.uid() is null then raise exception 'Faça login para continuar'; end if;
  select coalesce((owned ->> p_card_id::text)::integer,0) into owned_count
  from public.album_progress where user_id = auth.uid();
  if owned_count < 1 then raise exception 'Você ainda não possui esta figurinha'; end if;
  insert into public.feed_posts(user_id,card_id,caption)
  values(auth.uid(),p_card_id,left(trim(coalesce(p_caption,'')),180)) returning id into new_id;
  return new_id;
end;
$$;

create or replace function public.send_friend_request(p_handle text)
returns void language plpgsql security definer set search_path = public as $$
declare target_id uuid; reverse_id bigint;
begin
  select user_id into target_id from public.social_profiles where handle = lower(trim(p_handle));
  if target_id is null then raise exception 'Colecionador não encontrado'; end if;
  if target_id = auth.uid() then raise exception 'Você não pode adicionar a si mesmo'; end if;
  select id into reverse_id from public.friendships where requester_id=target_id and addressee_id=auth.uid();
  if reverse_id is not null then
    update public.friendships set status='accepted',updated_at=now() where id=reverse_id;
    return;
  end if;
  insert into public.friendships(requester_id,addressee_id,status)
  values(auth.uid(),target_id,'pending')
  on conflict(requester_id,addressee_id) do update set status='pending',updated_at=now();
end;
$$;

create or replace function public.respond_friend_request(p_friendship_id bigint, p_accept boolean)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.friendships set status=case when p_accept then 'accepted' else 'rejected' end,updated_at=now()
  where id=p_friendship_id and addressee_id=auth.uid() and status='pending';
  if not found then raise exception 'Convite não encontrado'; end if;
end;
$$;

create or replace function public.propose_sticker_trade(p_friend uuid, p_offered integer, p_requested integer)
returns bigint language plpgsql security definer set search_path = public as $$
declare offered_count integer; requested_count integer; new_id bigint;
begin
  if not exists(select 1 from public.friendships f where f.status='accepted' and ((f.requester_id=auth.uid() and f.addressee_id=p_friend) or (f.addressee_id=auth.uid() and f.requester_id=p_friend))) then
    raise exception 'As trocas só podem ser feitas entre amigos';
  end if;
  select coalesce((owned ->> p_offered::text)::integer,0) into offered_count from public.album_progress where user_id=auth.uid();
  select coalesce((owned ->> p_requested::text)::integer,0) into requested_count from public.album_progress where user_id=p_friend;
  if offered_count < 1 then raise exception 'Você não possui a figurinha oferecida'; end if;
  if requested_count < 1 then raise exception 'Seu amigo não possui a figurinha pedida'; end if;
  insert into public.sticker_trades(proposer_id,recipient_id,offered_card_id,requested_card_id)
  values(auth.uid(),p_friend,p_offered,p_requested) returning id into new_id;
  return new_id;
end;
$$;

create or replace function public.respond_sticker_trade(p_trade_id bigint, p_accept boolean)
returns void language plpgsql security definer set search_path = public as $$
declare t public.sticker_trades%rowtype; proposer_owned jsonb; recipient_owned jsonb; offer_count integer; request_count integer;
begin
  select * into t from public.sticker_trades where id=p_trade_id and recipient_id=auth.uid() and status='pending' for update;
  if not found then raise exception 'Troca não encontrada'; end if;
  if not p_accept then update public.sticker_trades set status='rejected',resolved_at=now() where id=t.id; return; end if;
  select owned into proposer_owned from public.album_progress where user_id=t.proposer_id for update;
  select owned into recipient_owned from public.album_progress where user_id=t.recipient_id for update;
  offer_count := coalesce((proposer_owned ->> t.offered_card_id::text)::integer,0);
  request_count := coalesce((recipient_owned ->> t.requested_card_id::text)::integer,0);
  if offer_count < 1 or request_count < 1 then raise exception 'Uma das figurinhas não está mais disponível'; end if;
  proposer_owned := jsonb_set(proposer_owned,array[t.offered_card_id::text],to_jsonb(offer_count-1),true);
  proposer_owned := jsonb_set(proposer_owned,array[t.requested_card_id::text],to_jsonb(coalesce((proposer_owned->>t.requested_card_id::text)::integer,0)+1),true);
  recipient_owned := jsonb_set(recipient_owned,array[t.requested_card_id::text],to_jsonb(request_count-1),true);
  recipient_owned := jsonb_set(recipient_owned,array[t.offered_card_id::text],to_jsonb(coalesce((recipient_owned->>t.offered_card_id::text)::integer,0)+1),true);
  update public.album_progress set owned=proposer_owned,updated_at=now() where user_id=t.proposer_id;
  update public.album_progress set owned=recipient_owned,updated_at=now() where user_id=t.recipient_id;
  update public.sticker_trades set status='accepted',resolved_at=now() where id=t.id;
end;
$$;

create or replace function public.cancel_sticker_trade(p_trade_id bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.sticker_trades set status='cancelled',resolved_at=now()
  where id=p_trade_id and proposer_id=auth.uid() and status='pending';
  if not found then raise exception 'Troca não encontrada'; end if;
end;
$$;

revoke all on function public.set_featured_sticker(integer) from public,anon;
revoke all on function public.publish_sticker(integer,text) from public,anon;
revoke all on function public.send_friend_request(text) from public,anon;
revoke all on function public.respond_friend_request(bigint,boolean) from public,anon;
revoke all on function public.propose_sticker_trade(uuid,integer,integer) from public,anon;
revoke all on function public.respond_sticker_trade(bigint,boolean) from public,anon;
revoke all on function public.cancel_sticker_trade(bigint) from public,anon;
grant execute on function public.set_featured_sticker(integer), public.publish_sticker(integer,text), public.send_friend_request(text), public.respond_friend_request(bigint,boolean), public.propose_sticker_trade(uuid,integer,integer), public.respond_sticker_trade(bigint,boolean), public.cancel_sticker_trade(bigint) to authenticated;

create or replace function public.complete_daily_activity(p_activity text, p_score integer)
returns jsonb language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid(); today_local date := (now() at time zone 'America/Fortaleza')::date; activities jsonb; activity_date date; coin_balance integer; reward integer; minimum_score integer;
begin
  if uid is null then raise exception 'Faça login para continuar'; end if;
  if p_activity not in ('memory','quiz','caju') then raise exception 'Missão inválida'; end if;
  reward := case p_activity when 'memory' then 8 when 'quiz' then 6 else 10 end;
  minimum_score := case p_activity when 'memory' then 6 when 'quiz' then 3 else 10 end;
  if p_score < minimum_score then raise exception 'Complete o desafio antes de resgatar a recompensa'; end if;
  select daily_activities,daily_activity_date,coins into activities,activity_date,coin_balance from public.album_progress where user_id=uid for update;
  if activity_date is distinct from today_local then activities:='{}'::jsonb; activity_date:=today_local; end if;
  if coalesce((activities->>p_activity)::boolean,false) then raise exception 'Esta missão já foi concluída hoje'; end if;
  activities:=jsonb_set(activities,array[p_activity],'true'::jsonb,true); coin_balance:=coin_balance+reward;
  update public.album_progress set daily_activities=activities,daily_activity_date=activity_date,coins=coin_balance,updated_at=now() where user_id=uid;
  return jsonb_build_object('activity',p_activity,'reward',reward,'coins',coin_balance,'activities',activities,'activity_date',activity_date);
end;
$$;
